import type { Metadata } from "next";
import { Montserrat, Oxanium } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const oxanium = Oxanium({
	subsets: ["latin"],
	weight: ["500", "600"],
	variable: "--font-oxanium",
});
const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["400", "600"],
	variable: "--font-montserrat",
});

export const metadata: Metadata = {
	title: "NLW Connect - devstage",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-BR"
			className={cn(
				montserrat.className,
				oxanium.className,
				"dark antialiased"
			)}
		>
			<body>{children}</body>
		</html>
	);
}
