import type { Metadata } from "next";
import { Montserrat, Oxanium } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const oxanium = Oxanium({
	subsets: ["latin"],
	weight: ["500", "600"],
	variable: "--font-oxanium",
});
const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["400", "600"],
	variable: "--font-montserrat",
});

export const metadata: Metadata = {
	title: "NLW Connect - devstage",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-BR"
			className={cn(
				montserrat.className,
				oxanium.className,
				"dark antialiased"
			)}
		>
			<body className="bg-[url('/background.png')] bg-top bg-no-repeat md:bg-right-top">
				<main className="mx-auto max-w-screen-xl px-5 py-8 md:py-0">
					{children}
				</main>
				<Toaster />
			</body>
		</html>
	);
}
