name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: bun install

      - name: Run Biome Check
        run: bun biome:check

      - name: Test TypeScript Syntax
        run: bun type-check

      - name: Build
        run: bun build
